version: "3.9"
services:
    crawler:
        container_name: spiegel-crawler
        build: .
        env_file:
            - env.default
        depends_on: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        restart: on-failure
        ports:
            - 27017:27017
        env_file:
            - env.default